image: node:10.15.3

pipelines:
  default:
    - step:
        # runs-on: self.hosted
        name: 'Setup'
        caches:
          - nodecustom
          - yarncustom
        script:
          - yarn
          - yarn lint
          - yarn test
    - step:
        name: 'Deploy'
        script:
            - pipe: atlassian/ssh-run:0.2.3
              variables:
                SSH_USER: 'bloodrizer'
                SERVER: '104.248.76.129'
                MODE: 'command'
                COMMAND: '/var/www/kittensgame.com/html/deploy.sh'
                
                
definitions:
  caches:
    nodecustom: ./node_modules
    yarncustom: /usr/local/share/.cache/yarn
